# Docker compose file for building docker images and running locally

version: '3.8'

services:
  book_catalog:
    build:
     context: ./book_catalog
     dockerfile: Dockerfile
    image: book_catalog
    ports:
      - "8001:80"
    environment:
      - DATABASE_URL=postgresql://sit722_9_2d_5px0_user:fqJp0kBfKJyIFQ8wLL5azZOcMupx7Moy@dpg-crsq0ltds78s73e88ja0-a.oregon-postgres.render.com/sit722_9_2d_5px0
    networks:
      - app-networks

  inventory_management:
    build:
     context: ./inventory_management
     dockerfile: Dockerfile
    image: inventory_management
    ports:
      - "8002:80"
    environment:
     - DATABASE_URL=postgresql://sit722_9_2d_5px0_user:fqJp0kBfKJyIFQ8wLL5azZOcMupx7Moy@dpg-crsq0ltds78s73e88ja0-a.oregon-postgres.render.com/sit722_9_2d_5px0
    networks:
      - app-networks

networks:
  app-networks:
    driver: bridge